"""initial schema

Revision ID: 6be85614a18c
Revises: 
Create Date: 2026-09-12 10:29:07.141348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be85614a18c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=255), nullable=False),
    sa.Column('indicator_type', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('case_ref', sa.String(length=32), nullable=False),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('onchain_status', sa.String(length=24), nullable=False),
    sa.Column('onchain_tx_hash', sa.String(length=80), nullable=True),
    sa.Column('onchain_network', sa.String(length=32), nullable=True),
    sa.Column('onchain_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('onchain_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_index')
    )
    with op.batch_alter_table('chain_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_blocks_case_ref'), ['case_ref'], unique=False)

    op.create_table('feedback_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_ref', sa.String(length=32), nullable=True),
    sa.Column('verdict', sa.String(length=24), nullable=True),
    sa.Column('used_in_training', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('case_ref', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('sender_from', sa.String(length=512), nullable=True),
    sa.Column('sender_domain', sa.String(length=255), nullable=True),
    sa.Column('originating_ip', sa.String(length=64), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('ml_probability', sa.Float(), nullable=True),
    sa.Column('spf_result', sa.String(length=16), nullable=True),
    sa.Column('dkim_result', sa.String(length=32), nullable=True),
    sa.Column('dmarc_result', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('asn', sa.String(length=64), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=True),
    sa.Column('hash_generated_at', sa.DateTime(), nullable=True),
    sa.Column('analyst_verdict', sa.String(length=24), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('report_path', sa.String(length=512), nullable=True),
    sa.Column('raw_email_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_ref')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_owner_id'), ['owner_id'], unique=False)

    op.create_table('mailbox_oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('mailbox_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    with op.batch_alter_table('mailbox_oauth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailbox_oauth_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mailbox_oauth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailbox_oauth_tokens_user_id'))

    op.drop_table('mailbox_oauth_tokens')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_owner_id'))

    op.drop_table('cases')
    op.drop_table('users')
    op.drop_table('feedback_log')
    with op.batch_alter_table('chain_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_blocks_case_ref'))

    op.drop_table('chain_blocks')
    op.drop_table('blacklist_entries')
    # ### end Alembic commands ###
