"""Initial database schema

Revision ID: 724751ceac94
Revises: 
Create Date: 2026-09-11 20:47:49.086328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724751ceac94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cases_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key( 'fk_cases_owner_id_users', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cases_owner_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cases_owner_id'))
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
